[package]
name = "lxcup-test-support"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
chrono.workspace = true
lxcup-agent = { path = "../lxcup-agent" }
lxcup-core = { path = "../lxcup-core" }
lxcup-proxmox = { path = "../lxcup-proxmox" }
tokio.workspace = true
uuid.workspace = true
url.workspace = true
