[package]
name = "lxcup-discovery"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
chrono.workspace = true
lxcup-core = { path = "../lxcup-core" }
lxcup-persistence = { path = "../lxcup-persistence" }
lxcup-proxmox = { path = "../lxcup-proxmox" }
thiserror.workspace = true
tokio.workspace = true
